# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Build app for release
      run: msbuild SimHubHaptics.csproj /property:GenerateFullPaths=true /t:build /p:Configuration=Debug /p:Platform=AnyCPU /consoleloggerparameters:NoSummar
    - run: Compress-Archive -Path "C:\Program Files (x86)\SimHub\" -DestinationPath "C:\SimHubHaptics.zip"
    - uses: Shopify/upload-to-release@v2.0.0
      with:
        name: SimHubHaptics.zip
        path: C:\SimHubHaptics.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}
